[package]
name = "example_lib"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
runtime = { path = "../../modules/runtime" }
macros = { path = "../../modules/macros" }
