[package]
name = "saturnus_rt"
version = "0.1.0"
edition = "2024"

[dependencies]
minijinja = "2.9.0"
mlua = { version = "0.10", features = ["lua53", "vendored"] }
regex = "1.11.1"
reqwest = { version = "0.12.15", features = ["blocking"] }
serde = "1.0.219"
serde_json = "1.0.140"
toml = "0.8.22"
